### ISSUE TITLE
[ Internal ] Complete Reading

### ISSUE THREAD

**Issue by harshasrikara** [OctoPipeline/octopipeline#1]
### Summary
Given our choice to go with a NextJS stack, its important for everyone to be comfortable with specific areas . This issue serves as a place to centralize the necessary reading to ensure that you will have maximum chance of success when developing. Note: For each person there's only 1-2 reading pages assigned. These will provide the minimum amount of information required to get developing. However, to truly maximize your potential to contribute throughout, I recommend reading up as much as possible.

### Task List | All
 - [ ] [NextJS Home](https://nextjs.org)
 - [ ] [Typescript in 5 minutes](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html)

##### @Joy2469 

 - [ ] [Creating Pages](https://nextjs.org/docs/basic-features/pages)
 - [ ] [Managing CSS](https://nextjs.org/docs/basic-features/built-in-css-support)

##### @aashish2057 

 - [ ] [Routing](https://nextjs.org/docs/routing/introduction)
 - [ ] [SSR](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)
 - [ ] [SWR](https://nextjs.org/docs/basic-features/data-fetching#swr)

##### @aemmadi 

 - [ ] [API Routing](https://nextjs.org/docs/api-routes/introduction)
 - [ ] [Next Auth](https://next-auth.js.org)

##### @spenpal2000 

 - [ ] [Axios](https://axios-http.com/docs/example)
 - [ ] [Docker Basics](https://medium.com/codingthesmartway-com-blog/docker-beginners-guide-part-1-images-containers-6f3507fffc98)

##### @harshasrikara 

 - [ ] Reading

### Additional Context
Although each person only has a small amount of reading before you're off coding, I'd recommend giving a glance through the remainder of the reading associated with everyone else. It'll be really helpful when working with the entire stack top to bottom.
