### ISSUE TITLE
[Feature] Add API endpoints to perform CRUD operations on users and requests

### ISSUE THREAD

**Issue by harshasrikara** [OctoPipeline/octopipeline#12]
**Summary**
Be able to work with request and user objects. Use CRUD APIs to read and write data to mongoDB.

**Task List**
 - [x] Create mongoose schemas for User & Request based on MVP discussions
 - [x] Add CRUD APIs for User Schema
 - [x] Add CRUD APIs for Request Schema
 - [x] Add appropriate error handling for invalid schemas
