### ISSUE TITLE
[Feature] Profile Page

### ISSUE THREAD

**Issue by harshasrikara** [OctoPipeline/octopipeline#19]
**Summary**
A user after signing in should be directed to this page. Displays their profile, any relevant custom attributes and work with requests.

**Task List**
 - [x] Only display page when authenticated at `/profile`
 - [x] Display user information (name, email, # of submitted requests, # of approved requests, etc)
 - [x] Fill with dummy data for now ^^
 - [x] Add buttons / side panel / tab / etc to house set of options (listed below)
 - [x] Include options to navigate to print page (to submit a new request)
 - [ ] Display list of submitted requests and include option to edit & delete

**Additional context**
Until LDAP issue is merged can display a dummy username / email. Same goes for all the other fields, feel free to populate with dummy values.
