### ISSUE TITLE
[Feature] OctoPrint API

### ISSUE THREAD

**Issue by harshasrikara** [OctoPipeline/octopipeline#2]
**Summary**
Be able to send a print job off to the OctoPrint Simulator

**Task List**
 - [x] Be able to run the OctoPrint simulator locally
 - [x] Be able to interact with the simulator over the API
 - [ ] Create an API endpoint that accepts any/all parameters required and passes them along to the API

**Additional context**
For this issue it suffices to create a standalone `.js / .ts` file that has a function accepting the parameters you need & then makes the required API calls to the OctoPrint simulator. Converting that into an API endpoint in the project is very straightforward and shouldn't pose a challenge to the development of this feature.
