### ISSUE TITLE
[Feature] Admin console

### ISSUE THREAD

**Issue by harshasrikara** [OctoPipeline/octopipeline#20]
**Summary**
Create a page for administrators to access submitted requests and approve / reject them

**Task List**
 - [ ] Show list of submitted requests
 - [ ] Each request should have option to click on and open viewer
 - [ ] If viewer detects that admin is signed in should display options to approve / reject

**Additional context**
The viewer described here is just the print page editor
