### ISSUE TITLE
[Feature] Dockerize Application

### ISSUE THREAD

**Issue by harshasrikara** [OctoPipeline/octopipeline#5]
**Summary**
Be able to run the NextJS application through docker. 

**Task List**
 - [x] Add Dockerfile for building the image
 - [x] Update docker-compose to include the newly built image
 - [x] Expose ports as required to allow external usage of the application

**Additional context**
This might potentially involve setting up a CI/CD process on the repo to allow for the project to continuously build after merging pull requests and then uploading the image to a registry. 

 - [Next JS Dockerize Documentation](https://nextjs.org/docs/deployment#docker-image)
