### ISSUE TITLE
[Feature] 3D Printing Page

### ISSUE THREAD

**Issue by aashish2057** [OctoPipeline/octopipeline#6]
**Summary**
Create page for user to upload 3d print file, see 3d visualization of print job and push file to admin's for approval

**Text Fields**
- Submission Name
- Printer Name : DropDown of different printers available with a sort blurb under. (config file so operators could edit the printers available)
- Filament Color: Color Option (confiq file so it can be updates frequently)
- if a printer with two filament option is selected provide an option for two filaments.

**Task List**
 - [ ] Instructions to convert 3D print file to GCode
 - [x] File Upload section (drag and drop)
 - [ ] Render a visual representation of the file
 - [ ] Text Fields
 - [ ] Showcase the hours the file will require to be printed
 - [ ] Cost of printing.
 - [ ] Submit all necessary information to back end when user clicks print button

**Additional context**
https://www.figma.com/file/3C0fWZdnSGlz8fnSQOFqBT/UTDesign-Makerspace?node-id=0%3A1

**Comment by harshasrikara** [comment]
This component needs to be made modular enough to support 2-way communication between frontend and backend. This same component should be re-used for all the edit pages which involves reading a pre-submitted request / file data and displaying that information to the user. Additionally should be able to switch between all of these forms based on the identity / meta information about the signed in user (whether they are user or admin), and whether its for submitting a new form or editing an existing one.
