### ISSUE TITLE
[Feature] Home Page

### ISSUE THREAD

**Issue by aashish2057** [OctoPipeline/octopipeline#7]
**Summary**
Create Home page to summarize application for new users

**Task List**
 - [x] Implement Nav Bar
 - [x] Create Hamburger menu on left side of nav bar that has account and logout buttons
 - [x] In Body summarize 3d Printing
 - [x] In Body link to external resources
 - [x] Start printing button that connect to 3D printing Page

**Additional context**
https://www.figma.com/file/3C0fWZdnSGlz8fnSQOFqBT/UTDesign-Makerspace?node-id=0%3A1
